export const DWK_57172_PROFILE_VERSION = "dwkid-57172-rev-k";

export const DWK_57172_HEADERS = Object.freeze([
  "ECN Number",
  "Status",
  "Comment/Updates",
  "ECN Type",
  "Priority",
  "Requested By",
  "Customer",
  "Item Number",
  "Item Description",
  "Effective When",
  "Description of Change or New or Discontinued Item",
  "Marketing & Project Management Contact approval",
  "Engineering Contact approval",
  "Quality Contact approval",
  "Materials Contact approval",
  "Production Auto-Pack approval",
  "Production Contact approval",
  "Operations Contact approval",
  "Customer Service Contact approval",
  "Pricing Contact approval",
  "Finance Contact approval",
  "Marketing & Project Management Approval Date",
  "Marketing & Project Management Contact",
  "Engineering Approval Date",
  "Engineering Contact",
  "Quality Approval Date",
  "Quality Contact",
  "Materials Approval Date",
  "Materials Approval Contact",
  "Production Auto-Pack Approval Date",
  "Production Auto-Pack Contact",
  "Production Approval Date",
  "Production Contact",
  "Operations Approval Date",
  "Operations Contact",
  "Customer Service Approval Date",
  "Customer Service Contact",
  "Pricing Approval Date",
  "Pricing Contact",
  "Finance Approval Date",
  "Finance Approval Contact",
  "VP Quality - Customer Notification Approval",
  "Marketing - Customer Notification Approval",
  "Purchasing/Planning has Reviewed",
  "Purchasing has reviewed",
  "Planning has Reviewed",
  "Pricing has Reviewed",
  "Purchasing/Planning",
  "Purchasing",
  "Planning",
  "Pricing",
  "Marketing - Packaging Spec Approvals",
  "Engineering - Packaging Spec Approvals",
  "Quality - Packaging Spec Approvals",
  "Production Autopack - Packaging Spec Approvals",
  "Production - Packaging Spec Approvals",
  "ECN START DATE",
  "ECN COMPLETED DATE",
  "Days to Complete",
  "Duration",
  "Comments / Updates",
  "Approval Status",
  "Allocation %",
  "Predecessors",
  "Baseline Start",
  "Baseline Finish",
  "Variance",
]);

export const DWK_57172_BINDINGS = Object.freeze({
  ecnNumber: "ECN Number#1",
  status: "Status#2",
  actionType: "ECN Type#4",
  priority: "Priority#5",
  requestedBy: "Requested By#6",
  itemNumber: "Item Number#8",
  itemDescription: "Item Description#9",
  effectTiming: "Effective When#10",
  detailedDescription: "Description of Change or New or Discontinued Item#11",
});

export const DWK_57172_STATUS_ALIASES = Object.freeze({
  "In Preparation": "Submitted",
  "Initial Review": "MDC Validation",
  "ON HOLD": "Needs Info",
  "Sent for Approvals": "Pre-Approval",
  "Declined - Awaiting Further Action": "Rework",
  Approved: "Implementation",
  "Approved - Awaiting Further Action": "Implementation",
  "Sent for Packaging Spec Approvals": "MDC Verification",
  "Customer Service - Awaiting Further Action": "Implementation Review",
  "Sent for Customer Notification Approval": "Notifications",
  "Customer Notification - To be sent": "Notifications",
  "Customer Notification - Awaiting Response": "Notifications",
  "Deleted/Canceled": "Closed",
});

function normalizeHeader(value) {
  return String(value ?? "").normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("en-US");
}

export function matchesDwk57172Headers(headers) {
  return Array.isArray(headers) &&
    headers.length === DWK_57172_HEADERS.length &&
    headers.every((header, index) => normalizeHeader(header) === normalizeHeader(DWK_57172_HEADERS[index]));
}
