/**
 * Built-in ECN rules used when no reviewed private import has been activated.
 *
 * The supplied source documents are confidential and intentionally are not
 * embedded here.  Rules contain only normalized facts and short source
 * locators.  An imported, reviewed ruleset may replace this baseline at
 * runtime (see rulesetStore.js).
 */

export const ECN_RULESET_VERSION = "ecn-pilot-2026.08.1";

export const EVIDENCE_LEVELS = Object.freeze([
  "controlled",
  "provisional_redline",
  "unresolved_comment",
  "example_screenshot",
  "conflict",
]);

export const DEPARTMENTS = Object.freeze({
  ENGINEERING: "Engineering",
  QUALITY: "Quality",
  SUPPLY_CHAIN: "Supply Chain",
  PRODUCT_MANAGEMENT: "Product Management",
  PROJECT_MANAGEMENT: "Project Management",
  PRODUCTION: "Production",
  FINANCE: "Finance",
  PRICING: "Pricing",
  CUSTOMER_SERVICE: "Customer Service",
});

const D = DEPARTMENTS;

const evidence = (
  source,
  section,
  {
    revision = "supplied-controlled-copy",
    cellRange = null,
    evidenceLevel = "controlled",
    condition = "always",
    severity = "blocker",
    expectedValue = "provided",
    nextAction = "Confirm and supply the required evidence.",
  } = {},
) => ({
  source,
  revision,
  section,
  cellRange,
  condition,
  severity: evidenceLevel === "controlled" || severity !== "blocker" ? severity : "warning",
  expectedValue,
  nextAction,
  evidenceLevel,
});

const MATRIX_ROW_BY_ID = Object.freeze({
  form_fit_function_catalog: 18,
  form_fit_function_custom: 19,
  source_catalog: 20,
  source_custom: 21,
  secondary_process_catalog: 22,
  secondary_process_custom: 23,
  quality_improvement: 24,
  manufacturing_process_change: 25,
  new_custom_packager: 26,
  new_catalog_packager: 27,
  discontinuation_reactivation: 28,
  branding_artwork: 29,
  packaging_catalog: 30,
  packaging_custom: 31,
  cost_catalog: 32,
  cost_custom: 33,
  engineering_minor_document: 34,
  routing_change: 35,
  custom_routing: 36,
  catalog_routing_rate: 37,
  custom_routing_rate: 38,
  qa_block: 39,
  incoming_inspection_flag_text: 40,
  po_text_quality: 41,
  po_text_vendor_information: 42,
});

const matrixSource = (id, label) => {
  const row = MATRIX_ROW_BY_ID[id];
  return evidence("DWKID-7206 / ECN Approver-Reviewer-Notify Matrix", `Matrix row: ${label}`, {
    cellRange: row ? `Sheet1!A${row}:AJ${row}` : null,
    severity: "info",
    expectedValue: "route participants",
    nextAction: "Route the ECN to every required participant.",
  });
};

const route = (id, label, aliases, preApprovers, reviewers, recipients) => ({
  id,
  label,
  aliases,
  preApprovers,
  reviewers,
  recipients,
  ...matrixSource(id, label),
});

/** Exact normalized routing rows from the supplied 25-type matrix. */
export const CHANGE_TYPE_ROUTES = Object.freeze([
  route(
    "form_fit_function_catalog",
    "Form/Fit/Function - Catalog",
    ["FFF Catalog", "Form Fit Function Catalog", "Fit Form Function Catalog"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.PRICING, D.CUSTOMER_SERVICE],
  ),
  route(
    "form_fit_function_custom",
    "Form/Fit/Function - Custom",
    ["FFF Custom", "Form Fit Function Custom", "Fit Form Function Custom"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT, D.PRODUCTION, D.PRICING, D.CUSTOMER_SERVICE],
  ),
  route(
    "source_catalog",
    "Source - Catalog",
    ["Source Catalog", "Sourcing Catalog", "Source Change Catalog"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.PRICING, D.CUSTOMER_SERVICE],
  ),
  route(
    "source_custom",
    "Source - Custom",
    ["Source Custom", "Sourcing Custom", "Source Change Custom"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT, D.PRODUCTION, D.PRICING, D.CUSTOMER_SERVICE],
  ),
  route(
    "secondary_process_catalog",
    "Secondary Process - Catalog",
    ["Secondary Process Catalog"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT],
    [D.SUPPLY_CHAIN],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT],
  ),
  route(
    "secondary_process_custom",
    "Secondary Process - Custom",
    ["Secondary Process Custom"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT],
    [D.SUPPLY_CHAIN],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT],
  ),
  route(
    "quality_improvement",
    "Quality Improvement",
    ["Quality Change", "Quality Improvement Change"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [],
    [D.QUALITY, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "manufacturing_process_change",
    "Manufacturing Process Change",
    ["Manufacturing Process", "Process Change"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.SUPPLY_CHAIN],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "new_custom_packager",
    "New Custom/Packager",
    ["New Custom", "New Packager", "New Custom Packager"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT, D.PRODUCTION, D.PRICING],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.PRODUCTION],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT, D.PRODUCTION, D.PRICING],
  ),
  route(
    "new_catalog_packager",
    "New Catalog/Packager",
    ["New Catalog", "New Catalog Packager"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.PRICING, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.PRICING, D.CUSTOMER_SERVICE],
  ),
  route(
    "discontinuation_reactivation",
    "Discontinuation/Reactivation",
    ["Discontinuation", "Reactivation", "Obsolescence"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.CUSTOMER_SERVICE],
    [D.SUPPLY_CHAIN, D.CUSTOMER_SERVICE],
    [D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT, D.PRODUCTION, D.PRICING, D.CUSTOMER_SERVICE],
  ),
  route(
    "branding_artwork",
    "Branding/Artwork",
    ["Branding", "Artwork", "Label Artwork"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.PRODUCTION],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "packaging_catalog",
    "Packaging - Catalog",
    ["Packaging Catalog", "Package Catalog"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "packaging_custom",
    "Packaging - Custom",
    ["Packaging Custom", "Package Custom"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.ENGINEERING, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "cost_catalog",
    "Cost - Catalog",
    ["Cost Catalog", "Catalog Cost"],
    [D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE, D.PRICING],
    [D.SUPPLY_CHAIN],
    [D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE, D.PRICING],
  ),
  route(
    "cost_custom",
    "Cost - Custom",
    ["Cost Custom", "Custom Cost"],
    [D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE, D.PRICING],
    [D.SUPPLY_CHAIN],
    [D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE, D.PRICING],
  ),
  route(
    "engineering_minor_document",
    "Engineering Minor Document",
    ["Minor Engineering Document", "Engineering Document Minor"],
    [D.ENGINEERING, D.QUALITY, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.ENGINEERING, D.PRODUCTION],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "routing_change",
    "Routing Change",
    ["Catalog Routing", "Routing"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.SUPPLY_CHAIN],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "custom_routing",
    "Custom Routing",
    ["Custom Routing Change"],
    [D.ENGINEERING, D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION],
    [D.SUPPLY_CHAIN],
    [D.ENGINEERING, D.PRODUCT_MANAGEMENT, D.PROJECT_MANAGEMENT, D.PRODUCTION],
  ),
  route(
    "catalog_routing_rate",
    "Catalog Routing Rate",
    ["Routing Rate Catalog", "Catalog Rate"],
    [D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE],
    [D.SUPPLY_CHAIN],
    [D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE],
  ),
  route(
    "custom_routing_rate",
    "Custom Routing Rate",
    ["Routing Rate Custom", "Custom Rate"],
    [D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE],
    [D.SUPPLY_CHAIN],
    [D.PRODUCT_MANAGEMENT, D.PRODUCTION, D.FINANCE],
  ),
  route(
    "qa_block",
    "QA Block",
    ["Quality Block", "Quality Assurance Block"],
    [D.SUPPLY_CHAIN, D.PRODUCTION],
    [D.SUPPLY_CHAIN],
    [D.PRODUCTION],
  ),
  route(
    "incoming_inspection_flag_text",
    "Incoming Inspection Flag/Text",
    ["Incoming Inspection", "Inspection Text", "Incoming Inspection Flag"],
    [D.SUPPLY_CHAIN, D.PRODUCTION],
    [D.SUPPLY_CHAIN],
    [D.PRODUCTION],
  ),
  route(
    "po_text_quality",
    "PO Text - Quality",
    ["Purchase Order Text Quality", "PO Quality Text"],
    [D.QUALITY, D.SUPPLY_CHAIN],
    [D.SUPPLY_CHAIN],
    [D.QUALITY],
  ),
  route(
    "po_text_vendor_information",
    "PO Text - Vendor Information",
    ["Purchase Order Text Vendor Information", "PO Vendor Text"],
    [D.QUALITY, D.SUPPLY_CHAIN, D.PRODUCT_MANAGEMENT],
    [D.SUPPLY_CHAIN],
    [D.QUALITY, D.PRODUCT_MANAGEMENT],
  ),
]);

const CHECKLIST_CELL_BY_PROFILE = Object.freeze({
  "New Purchased Material": Object.freeze({
    material_number: "E10",
    short_description: "E11",
    base_uom: "E12",
    material_group: "E13",
    product_hierarchy: "E14",
    product_attributes: "E14",
    harmonization_code: "E15",
    vendor_name: "E16",
    vendor_number: "E17",
    vendor_part_number: "E18",
    drawing: "E19",
    vendor_quote: "E20",
    standard_cost: "E21",
    lead_time: "E22",
    pricing: "E23",
    material_specifics: "E24",
    packaging_quantity: "E25",
    packaging_configuration: "E25",
    carton_dimensions: "E26",
    case_weight: "E27",
    country_of_origin: "E28",
  }),
  "New Manufactured Material": Object.freeze({
    material_number: "E31",
    short_description: "E32",
    base_uom: "E33",
    material_group: "E34",
    product_hierarchy: "E35",
    product_attributes: "E35",
    harmonization_code: "E36",
    standard_cost: "E37",
    pricing: "E38,E47",
    drawing: "E39",
    outside_operation_quote: "E40",
    packaging_quantity: "E41",
    packaging_configuration: "E41",
    carton_dimensions: "E42",
    case_weight: "E43",
    country_of_origin: "E44",
    bom: "E45",
    routing_work_centers: "E46",
    routing_rates: "E46",
    labeling: "E46",
  }),
  "Changed Purchased Material": Object.freeze({
    reason: "E50",
    item_number: "E51",
    where_used: "E52",
    catalog_custom: "E53",
    short_description: "E54",
    dimensional_old_new: "E55:E56",
    part_number_old_new: "E57:E58",
    packaging_old_new: "E59:E60",
    material_old_new: "E61:E62",
    validation_report: "E63:E64",
    supporting_documents: "E65",
    effective_date: "E66",
    remaining_inventory: "E67",
    coo_old_new: "E68:E69",
    change_description: "E70",
    vendor_quote: "E71",
    pricing: "E72",
    customer_notification: "E73",
    notification_template: "E74",
    standard_cost: "E75",
    drawing: "E76",
  }),
  "Changed Manufactured Material": Object.freeze({
    reason: "E79",
    item_number: "E80",
    where_used: "E81",
    catalog_custom: "E82",
    short_description: "E83",
    dimensional_old_new: "E84:E85",
    part_number_old_new: "E86:E87",
    process_explanation: "E88:E89",
    packaging_old_new: "E90:E91",
    artwork_label: "E92:E95",
    material_old_new: "E96:E97",
    supporting_documents: "E98",
    effective_date: "E99",
    inventory_disposition: "E100:E101",
    coo_old_new: "E102:E103",
    change_description: "E104",
    vendor_quote: "E105",
    customer_notification: "E106",
    revised_bom: "E107",
    revised_routing: "E108",
    standard_cost: "E109",
    notification_template: "E110",
  }),
  "Obsolescence/Reactivation": Object.freeze({
    reason: "E113",
    item_number: "E114",
    where_used: "E115",
    replacement: "E116:E117",
    remaining_inventory: "E118",
    inventory_disposition: "E118",
  }),
  "System Change": Object.freeze({
    description: "E125",
    reason: "E125",
    tasks_due_dates: "E126:E127",
    evidence: "E128:E129",
    approvers: "E130",
  }),
});

const checklistSource = (profile, item, id, options = {}) => {
  const coordinate = CHECKLIST_CELL_BY_PROFILE[profile]?.[id] || null;
  return evidence("DWKID-7205 / ECN Required Information Checklist", `${profile}: ${item}`, {
    ...options,
    cellRange: coordinate ? `Sheet1!${coordinate}` : options.cellRange || null,
  });
};

const required = (id, label, field, profile, options = {}) => ({
  id,
  label,
  fields: Array.isArray(field) ? field : [field],
  mode: options.mode || "any",
  ...checklistSource(profile, label, id, options),
});

const commonNew = (profile) => [
  required("material_number", "Material number", "itemNumber", profile),
  required("short_description", "40-character material description", "itemDescription", profile),
  required("base_uom", "Base unit of measure", "baseUom", profile),
  required("material_group", "Material group", "materialGroup", profile),
  required("product_hierarchy", "Product hierarchy", "productHierarchy", profile),
  required("product_attributes", "Product classification and attributes", "productAttributes", profile),
  required("harmonization_code", "Harmonization code", "harmonizationCode", profile),
  required("drawing", "Controlled drawing or drawing disposition", ["drawing", "drawingDisposition"], profile),
  required("standard_cost", "Material cost", "standardCost", profile),
  required("lead_time", "Lead time", "leadTime", profile),
  required("pricing", "Pricing information", "pricing", profile),
  required("material_specifics", "Material-specific master data", "materialSpecifics", profile),
  required("packaging_quantity", "Packaging quantities", "packagingQuantity", profile),
  required("packaging_configuration", "Packaging configuration", "packagingConfiguration", profile),
  required("carton_dimensions", "Carton dimensions", "cartonDimensions", profile),
  required("case_weight", "Case weight", "caseWeight", profile),
  required("country_of_origin", "Country of origin", "countryOfOrigin", profile),
];

const conditional = (id, label, field, profile, conditionField, options = {}) =>
  required(id, label, field, profile, {
    ...options,
    condition: { field: conditionField, operator: "truthy" },
  });

const NEW_PURCHASED = "New Purchased Material";
const NEW_MANUFACTURED = "New Manufactured Material";
const CHANGED_PURCHASED = "Changed Purchased Material";
const CHANGED_MANUFACTURED = "Changed Manufactured Material";
const OBSOLESCENCE = "Obsolescence/Reactivation";
const SYSTEM_CHANGE = "System Change";

export const CHECKLIST_PROFILES = Object.freeze({
  new_purchased: {
    id: "new_purchased",
    label: NEW_PURCHASED,
    sourceCellRange: "Sheet1!E9:E28",
    requirements: [
      ...commonNew(NEW_PURCHASED),
      required("vendor_name", "Vendor name", "vendorName", NEW_PURCHASED),
      required("vendor_number", "Vendor number", "vendorNumber", NEW_PURCHASED),
      required("vendor_part_number", "Vendor part number", "vendorPartNumber", NEW_PURCHASED),
      required("vendor_quote", "Vendor quote", "vendorQuote", NEW_PURCHASED),
    ],
  },
  new_manufactured: {
    id: "new_manufactured",
    label: NEW_MANUFACTURED,
    sourceCellRange: "Sheet1!E30:E47",
    requirements: [
      ...commonNew(NEW_MANUFACTURED).filter(
        (item) => !["lead_time", "material_specifics"].includes(item.id),
      ),
      required("bom", "Bill of material", "bom", NEW_MANUFACTURED),
      required("routing_work_centers", "Routing work centers", "routingWorkCenters", NEW_MANUFACTURED),
      required("routing_rates", "Routing rates", "routingRates", NEW_MANUFACTURED),
      required("labeling", "Labeling requirements", "labeling", NEW_MANUFACTURED),
      conditional(
        "outside_operation_quote",
        "Outside-operation quote",
        "outsideOperationQuote",
        NEW_MANUFACTURED,
        "outsideOperationRequired",
      ),
    ],
  },
  changed_purchased: {
    id: "changed_purchased",
    label: CHANGED_PURCHASED,
    sourceCellRange: "Sheet1!E49:E76",
    requirements: [
      required("reason", "Reason for change", "reason", CHANGED_PURCHASED),
      required("item_number", "Affected item number", "itemNumber", CHANGED_PURCHASED),
      required("where_used", "Where-used assessment", "whereUsed", CHANGED_PURCHASED),
      required("catalog_custom", "Catalog/custom classification", "catalogCustom", CHANGED_PURCHASED),
      required("short_description", "Material description", "itemDescription", CHANGED_PURCHASED),
      conditional("dimensional_old_new", "Old/new dimensional evidence", "dimensionalEvidence", CHANGED_PURCHASED, "dimensionalChange"),
      conditional("part_number_old_new", "Old/new vendor part number evidence", "partNumberEvidence", CHANGED_PURCHASED, "vendorPartNumberChange"),
      conditional("packaging_old_new", "Old/new packaging evidence", "packagingEvidence", CHANGED_PURCHASED, "packagingChange"),
      conditional("material_old_new", "Old/new material evidence", "materialEvidence", CHANGED_PURCHASED, "materialChange"),
      conditional("coo_old_new", "Old/new country-of-origin evidence", "countryOfOriginEvidence", CHANGED_PURCHASED, "countryOfOriginChange"),
      conditional("validation_report", "Sample validation report", "validationEvidence", CHANGED_PURCHASED, "validationRequired"),
      required("supporting_documents", "Supporting documents", "supportingDocuments", CHANGED_PURCHASED),
      required("effective_date", "Requested effective date", "effectiveDate", CHANGED_PURCHASED),
      required("remaining_inventory", "Remaining inventory and disposition", "remainingInventory", CHANGED_PURCHASED),
      required("change_description", "Detailed old/new change description", "detailedDescription", CHANGED_PURCHASED),
      conditional("vendor_quote", "Revised vendor quote", "vendorQuote", CHANGED_PURCHASED, "quoteRequired"),
      conditional("pricing", "Revised pricing", "pricing", CHANGED_PURCHASED, "pricingChange"),
      conditional("standard_cost", "Revised material cost", "standardCost", CHANGED_PURCHASED, "costChange"),
      conditional("drawing", "Revised drawing", "drawing", CHANGED_PURCHASED, "drawingRequired"),
      conditional("customer_notification", "Customer notification decision", "customerNotification", CHANGED_PURCHASED, "customerNotificationRequired"),
      conditional("notification_template", "Customer notification template", "notificationTemplate", CHANGED_PURCHASED, "customerNotificationRequired"),
    ],
  },
  changed_manufactured: {
    id: "changed_manufactured",
    label: CHANGED_MANUFACTURED,
    sourceCellRange: "Sheet1!E78:E110",
    requirements: [
      required("reason", "Reason for change", "reason", CHANGED_MANUFACTURED),
      required("item_number", "Affected item number", "itemNumber", CHANGED_MANUFACTURED),
      required("where_used", "Where-used assessment", "whereUsed", CHANGED_MANUFACTURED),
      required("catalog_custom", "Catalog/custom classification", "catalogCustom", CHANGED_MANUFACTURED),
      required("short_description", "Material description", "itemDescription", CHANGED_MANUFACTURED),
      required("process_explanation", "Manufacturing-process explanation", "processExplanation", CHANGED_MANUFACTURED),
      conditional("dimensional_old_new", "Old/new dimensional evidence", "dimensionalEvidence", CHANGED_MANUFACTURED, "dimensionalChange"),
      conditional("packaging_old_new", "Old/new packaging evidence", "packagingEvidence", CHANGED_MANUFACTURED, "packagingChange"),
      conditional("material_old_new", "Old/new material evidence", "materialEvidence", CHANGED_MANUFACTURED, "materialChange"),
      conditional("coo_old_new", "Old/new country-of-origin evidence", "countryOfOriginEvidence", CHANGED_MANUFACTURED, "countryOfOriginChange"),
      conditional("artwork_label", "Revised artwork or label", ["artwork", "labeling"], CHANGED_MANUFACTURED, "artworkChange"),
      required("supporting_documents", "Supporting documents", "supportingDocuments", CHANGED_MANUFACTURED),
      required("effective_date", "Requested effective date", "effectiveDate", CHANGED_MANUFACTURED),
      required("inventory_disposition", "Inventory disposition", "inventoryDisposition", CHANGED_MANUFACTURED),
      required("change_description", "Detailed old/new change description", "detailedDescription", CHANGED_MANUFACTURED),
      conditional("revised_bom", "Revised BOM", "bom", CHANGED_MANUFACTURED, "bomChange"),
      conditional("revised_routing", "Revised routing", "routing", CHANGED_MANUFACTURED, "routingChange"),
      conditional("standard_cost", "Revised material cost", "standardCost", CHANGED_MANUFACTURED, "costChange"),
      conditional("customer_notification", "Customer notification decision", "customerNotification", CHANGED_MANUFACTURED, "customerNotificationRequired"),
      conditional("notification_template", "Customer notification template", "notificationTemplate", CHANGED_MANUFACTURED, "customerNotificationRequired"),
    ],
  },
  obsolescence: {
    id: "obsolescence",
    label: OBSOLESCENCE,
    sourceCellRange: "Sheet1!E112:E118",
    requirements: [
      required("reason", "Reason for obsolescence/reactivation", "reason", OBSOLESCENCE),
      required("item_number", "Affected item number", "itemNumber", OBSOLESCENCE),
      required("where_used", "Where-used assessment", "whereUsed", OBSOLESCENCE),
      required("replacement", "Replacement material or explicit none", "replacementNumber", OBSOLESCENCE),
      required("remaining_inventory", "Remaining inventory", "remainingInventory", OBSOLESCENCE),
      required("inventory_disposition", "Inventory disposition", "inventoryDisposition", OBSOLESCENCE),
    ],
  },
  system_change: {
    id: "system_change",
    label: SYSTEM_CHANGE,
    sourceCellRange: "Sheet1!E124:E130",
    requirements: [
      required("description", "System-change description", "detailedDescription", SYSTEM_CHANGE, { evidenceLevel: "provisional_redline" }),
      required("reason", "Reason for system change", "reason", SYSTEM_CHANGE, { evidenceLevel: "provisional_redline" }),
      required("tasks_due_dates", "Tasks, owners, and due dates", "tasksDueDates", SYSTEM_CHANGE, { evidenceLevel: "provisional_redline" }),
      required("evidence", "Implementation evidence", "supportingDocuments", SYSTEM_CHANGE, { evidenceLevel: "provisional_redline" }),
      required("approvers", "System-change approvers", "systemApprovers", SYSTEM_CHANGE, { evidenceLevel: "provisional_redline" }),
    ],
  },
});

export const BASE_REQUEST_REQUIREMENTS = Object.freeze([
  required("requestor", "Requested By email", "requestedBy", "Engineering Change Control"),
  required("action_type", "Action type", "actionType", "Engineering Change Control"),
  required("priority", "Priority", "priority", "Engineering Change Control"),
  required("effect_timing", "Effect timing", "effectTiming", "Engineering Change Control"),
  required("item_number", "Item number", "itemNumber", "Engineering Change Control"),
  required("item_description", "Item description", "itemDescription", "Engineering Change Control"),
  required("detailed_description", "Detailed change description", "detailedDescription", "Engineering Change Control"),
  required("reason", "Reason for change", "reason", "Engineering Change Control"),
  required("affected_areas", "Affected areas", "affectedAreas", "Engineering Change Control"),
  required("supporting_documents", "Supporting documents or explicit none", "supportingDocuments", "Engineering Change Control"),
  required("risk_review", "Requestor risk review", "riskReview", "Engineering Change Control"),
]);

const crossCheck = (id, label, stage, options = {}) => ({
  id,
  label,
  stage,
  ...evidence("Engineering Change Control and linked work instructions", options.section || label, {
    condition: options.condition || "conditional",
    severity: options.severity || "blocker",
    expectedValue: options.expectedValue || "complete",
    nextAction: options.nextAction || "Supply or verify the required evidence.",
    evidenceLevel: options.evidenceLevel || "controlled",
  }),
});

export const CROSS_CHECK_RULES = Object.freeze([
  crossCheck("product_classification", "Product Classification Form for new items", "MDC Validation", {
    condition: "action type is New",
    expectedValue: "completed DWKID-69121",
  }),
  crossCheck("incoming_inspection", "Incoming inspection for New or Form/Fit/Function", "Implementation", {
    condition: "New item or Form/Fit/Function change",
    expectedValue: "incoming inspection decision and Inspection Text",
  }),
  crossCheck("customer_approval_timing", "Customer approval must not conflict with Immediately", "Pre-Approval", {
    condition: "customer approval or notification is required",
    expectedValue: "timing after approval and approval evidence",
  }),
  crossCheck("tier1_vial_memo", "Tier-1 vial source-change equivalency memo", "Pre-Approval", {
    condition: "Tier-1 vial in-source/out-source change",
    expectedValue: "Quality Equivalency Memo",
  }),
  crossCheck("conditional_drawing", "Conditional drawing evidence", "MDC Validation", {
    condition: "drawing required",
    expectedValue: "controlled drawing or explicit disposition",
  }),
  crossCheck("conditional_validation", "Conditional validation evidence", "MDC Verification", {
    condition: "validation required",
    expectedValue: "validation report/evidence",
  }),
  crossCheck("bom_uom_conversion", "BOM and UOM conversion", "Implementation", {
    condition: "new manufactured item, BOM change, or component UOM differs",
    expectedValue: "BOM plus required UOM conversion",
  }),
  crossCheck("routing_base_quantity", "Routing base quantity", "Implementation", {
    condition: "routing is created or changed",
    expectedValue: "verified routing base quantity",
  }),
  crossCheck("qa_authorization", "QA authorization", "Pre-Approval", {
    condition: "QA Block is removed",
    expectedValue: "documented QA authorization",
  }),
  crossCheck("hard_deletion_gates", "Hard-deletion inventory and demand gates", "Pre-Approval", {
    condition: "hard deletion requested",
    expectedValue: "zero inventory, open orders, forecast/demand, and where-used dependencies",
  }),
  crossCheck("closure_completion", "Review and notification completion before closure", "Closed", {
    condition: "status is Closed or closure is requested",
    expectedValue: "all reviewers and completion recipients complete",
  }),
]);

const playbook = (id, label, source, triggers, tasks, options = {}) => ({
  id,
  label,
  triggers,
  tasks: tasks.map((task, index) => ({
    id: `${id}.${index + 1}`,
    label: typeof task === "string" ? task : task.label,
    transaction: typeof task === "string" ? undefined : task.transaction,
    humanOnly: true,
  })),
  ...evidence(source, options.section || label, {
    severity: "info",
    expectedValue: "human-verified completion",
    nextAction: "Perform and verify the applicable checklist steps in SAP or document control.",
    evidenceLevel: options.evidenceLevel || "controlled",
  }),
});

export const PLAYBOOKS = Object.freeze([
  playbook("material_master", "Material Master", "2 Material Master", { actionTypes: ["new", "change", "delete"] }, [
    { label: "Create, change, or verify material master views", transaction: "MM01/MM02/MM03" },
    "Verify organizational views and field-level evidence",
  ], { evidenceLevel: "provisional_redline" }),
  playbook("numbering", "Origin of New Numbers", "3 Origin of New Numbers", { actionTypes: ["new"] }, [
    { label: "Verify the number origin and collision-free number assignment", transaction: "SE16N/MARA" },
  ]),
  playbook("bom", "Enter/Change BOM", "5 Enter-Change BOM", { profiles: ["new_manufactured"], fields: ["bomChange"] }, [
    { label: "Create/change and independently verify BOM", transaction: "CS01/CS02/CS03" },
    "Verify component quantities, base UOM, and any UOM conversion",
  ], { evidenceLevel: "provisional_redline" }),
  playbook("routing", "Enter/Change Routing", "6 Enter_Change Routing", { typeIds: ["routing_change", "custom_routing", "catalog_routing_rate", "custom_routing_rate"], profiles: ["new_manufactured"] }, [
    { label: "Create/change and independently verify routing", transaction: "CA01/CA02/CA03" },
    "Verify work centers, rates, and routing base quantity",
  ]),
  playbook("pricing", "Enter Pricing", "7 Enter Pricing", { typeIds: ["cost_catalog", "cost_custom", "new_custom_packager", "new_catalog_packager"], fields: ["pricingChange"] }, [
    { label: "Create/change and verify pricing condition", transaction: "VK11" },
  ], { evidenceLevel: "provisional_redline" }),
  playbook("costing", "Material Costing", "8 Material Costing", { typeIds: ["cost_catalog", "cost_custom"], fields: ["costChange"] }, [
    { label: "Run and review material cost estimate", transaction: "CK11N" },
    { label: "Release cost only after human approval", transaction: "CK24" },
  ]),
  playbook("purchasing_record", "Purchasing Info Record", "9 Create_Change Purchasing Info Record", { profiles: ["new_purchased", "changed_purchased"], fields: ["vendorPartNumberChange"] }, [
    { label: "Create/change and verify purchasing info record", transaction: "ME11/ME12" },
  ]),
  playbook("dms", "Document Management", "4 Engineering Document Request; 10 Document Management for Pallet Arrangements", { fields: ["drawingRequired", "artworkChange", "packagingChange"] }, [
    { label: "Create/change controlled document record and verify material link", transaction: "CV01N/CV02N; MM02" },
  ], { evidenceLevel: "conflict" }),
  playbook("qa_block", "QA Block", "15 QA Block", { typeIds: ["qa_block"] }, [
    { label: "Apply or remove QA distribution/plant status only with required authorization", transaction: "MM02" },
    "Record QA authorization for unblock/removal",
  ]),
  playbook("hard_deletion", "Hard Deletion", "16 Hard Deletion", { fields: ["hardDeletion"] }, [
    { label: "Verify stock, demand, open orders, forecast, and plant dependencies", transaction: "MD04; SE16N/MARC" },
    { label: "Resolve where-used dependencies before deletion", transaction: "CS20" },
    { label: "Apply plant-specific deletion sequence with human verification", transaction: "MM02" },
  ]),
  playbook("packaging", "Packaging Specification", "11 Packaging Specification Guideline", { typeIds: ["packaging_catalog", "packaging_custom"], fields: ["packagingChange"] }, [
    "Verify packaging quantities, configuration, dimensions, weights, and controlled specification",
  ]),
  playbook("labels", "Product Label Formatting", "12 Product Label Formatting Guideline", { typeIds: ["branding_artwork"], fields: ["artworkChange"] }, [
    "Verify product-label content, format, approvals, and controlled artwork",
  ]),
  playbook("customer_specifications", "Customer Specifications", "13 Customer Specifications", { fields: ["customerNotificationRequired"] }, [
    "Review customer-specific requirements and affected-customer where-used results",
  ]),
  playbook("customer_notification", "ECN Customer Notification", "14 Product Management ECN Customer Notification", { fields: ["customerNotificationRequired"] }, [
    "Prepare customer notification or approval package",
    "Record recipient completion before closure",
  ]),
  playbook("closure", "Engineering Change Control Closure", "1 Engineering Change Control", { statuses: ["closed", "notifications", "implementation review"] }, [
    "Verify implementation review completion",
    "Verify completion notifications and close only after all gates pass",
  ]),
]);

/** Header aliases are intentionally editable in an imported sheet profile. */
export const CANONICAL_FIELD_ALIASES = Object.freeze({
  ecnNumber: ["ecn number", "ecn #", "change number", "request number"],
  requestedBy: ["requested by", "requestor", "requester", "requested by email", "email"],
  actionType: ["action type", "action", "request action", "ecn action"],
  priority: ["priority", "request priority"],
  effectTiming: ["effect timing", "effectivity", "timing", "implementation timing", "effective timing"],
  itemNumber: ["item number", "material number", "part number", "sap material", "sap material number"],
  itemDescription: ["item description", "material description", "short description", "description 40"],
  detailedDescription: ["detailed description", "change description", "description of change", "old new description"],
  reason: ["reason", "reason for change", "business reason"],
  affectedAreas: ["affected areas", "impact areas", "areas affected"],
  supportingDocuments: ["supporting documents", "attachments", "supporting evidence", "documents"],
  riskReview: ["risk review", "requestor risk review", "risk assessment"],
  changeTypes: ["change type", "change types", "ecn type", "type of change"],
  status: ["status", "ecn status", "request status", "workflow status"],
  productManager: ["product manager", "pm", "assigned product manager"],
  materialOrigin: ["material origin", "procurement type", "make buy", "manufactured purchased"],
  baseUom: ["base uom", "base unit of measure", "uom"],
  materialGroup: ["material group"],
  productHierarchy: ["product hierarchy"],
  productAttributes: ["product attributes", "product classification", "classification attributes"],
  productClassificationForm: ["product classification form", "dwkid 69121", "classification form"],
  harmonizationCode: ["harmonization code", "hts code", "tariff code"],
  vendorName: ["vendor name", "supplier name"],
  vendorNumber: ["vendor number", "supplier number"],
  vendorPartNumber: ["vendor part number", "supplier part number"],
  drawing: ["drawing", "drawing number", "drawing evidence"],
  drawingDisposition: ["drawing disposition", "drawing not required reason"],
  drawingRequired: ["drawing required", "requires drawing"],
  vendorQuote: ["vendor quote", "supplier quote", "quote"],
  quoteRequired: ["quote required", "requires quote"],
  standardCost: ["standard cost", "material cost", "cost"],
  costChange: ["cost change", "cost impact", "cost changed"],
  leadTime: ["lead time", "planned delivery time"],
  pricing: ["pricing", "price", "sales price"],
  pricingChange: ["pricing change", "price change"],
  materialSpecifics: ["material specifics", "material master specifics"],
  packagingQuantity: ["packaging quantity", "pack quantity", "units per case"],
  packagingConfiguration: ["packaging configuration", "pallet configuration", "pack configuration"],
  cartonDimensions: ["carton dimensions", "case dimensions"],
  caseWeight: ["case weight", "carton weight"],
  countryOfOrigin: ["country of origin", "coo"],
  countryOfOriginChange: ["country of origin change", "coo change"],
  countryOfOriginEvidence: ["country of origin evidence", "coo old new"],
  bom: ["bom", "bill of material", "bill of materials", "revised bom"],
  bomChange: ["bom change", "bom required"],
  routing: ["routing", "revised routing"],
  routingChange: ["routing change", "routing required"],
  routingWorkCenters: ["routing work centers", "work centers"],
  routingRates: ["routing rates", "rates"],
  routingBaseQuantity: ["routing base quantity", "base quantity"],
  labeling: ["labeling", "label requirements", "label"],
  artwork: ["artwork", "label artwork"],
  artworkChange: ["artwork change", "label change", "branding change"],
  outsideOperationRequired: ["outside operation required", "outside processing"],
  outsideOperationQuote: ["outside operation quote", "outside processing quote"],
  whereUsed: ["where used", "where-used", "where used assessment"],
  replacementNumber: ["replacement", "replacement material", "replacement item number"],
  catalogCustom: ["catalog custom", "catalog or custom", "classification"],
  dimensionalChange: ["dimensional change", "dimension change"],
  dimensionalEvidence: ["dimensional evidence", "dimensions old new"],
  vendorPartNumberChange: ["vendor part number change", "supplier part change"],
  partNumberEvidence: ["part number evidence", "part number old new"],
  packagingChange: ["packaging change", "package change"],
  packagingEvidence: ["packaging evidence", "packaging old new"],
  materialChange: ["material change", "material composition change"],
  materialEvidence: ["material evidence", "material old new"],
  validationRequired: ["validation required", "requires validation", "sample validation required"],
  validationEvidence: ["validation evidence", "validation report", "sample validation report"],
  effectiveDate: ["effective date", "requested effective date"],
  remainingInventory: ["remaining inventory", "inventory", "stock on hand"],
  inventoryDisposition: ["inventory disposition", "stock disposition"],
  processExplanation: ["process explanation", "manufacturing process explanation"],
  customerNotificationRequired: ["customer notification required", "notify customer", "customer notification"],
  customerNotification: ["customer notification decision", "notification decision"],
  notificationTemplate: ["notification template", "customer notification template"],
  customerApprovalRequired: ["customer approval required", "requires customer approval"],
  customerApprovalEvidence: ["customer approval", "customer approval evidence", "approval received"],
  incomingInspection: ["incoming inspection", "incoming inspection flag", "inspection required"],
  inspectionText: ["inspection text", "incoming inspection text"],
  tier1VialSourceChange: ["tier 1 vial source change", "tier-1 vial", "vial in source out source"],
  tier1VialMemo: ["quality equivalency memo", "tier 1 vial memo", "vial memo"],
  componentUomDiffers: ["component uom differs", "uom differs", "component unit differs"],
  uomConversion: ["uom conversion", "unit of measure conversion"],
  qaBlockAction: ["qa block action", "quality block action", "block unblock"],
  qaAuthorization: ["qa authorization", "quality authorization", "qa approval"],
  hardDeletion: ["hard deletion", "hard delete", "deletion mode"],
  openOrders: ["open orders", "open purchase orders", "open production orders"],
  openForecast: ["open forecast", "forecast", "open demand"],
  reviewerCompletion: ["reviewer completion", "reviewers complete", "implementation review complete"],
  notificationCompletion: ["notification completion", "notifications complete", "recipients notified"],
  tasksDueDates: ["tasks due dates", "tasks owners due dates", "implementation tasks"],
  systemApprovers: ["system approvers", "approvers"],
  checklistProfile: ["checklist profile", "request profile", "material change profile"],
  closureRequested: ["closure requested", "ready to close", "close request"],
});

export const DEFAULT_ECN_RULESET = Object.freeze({
  kind: "ecn-ruleset",
  version: ECN_RULESET_VERSION,
  status: "active",
  createdAt: "2026-08-03T00:00:00.000Z",
  sourcePolicy: {
    storesRawSources: false,
    maximumExcerptLength: 240,
    blockerEvidenceLevel: "controlled",
  },
  evidenceLevels: EVIDENCE_LEVELS,
  // Names and delegates are intentionally absent from source control. A
  // reviewed private draft may populate this editable department -> names map.
  participantRoster: {},
  canonicalFieldAliases: CANONICAL_FIELD_ALIASES,
  changeTypes: CHANGE_TYPE_ROUTES,
  checklistProfiles: CHECKLIST_PROFILES,
  baseRequestRequirements: BASE_REQUEST_REQUIREMENTS,
  crossChecks: CROSS_CHECK_RULES,
  playbooks: PLAYBOOKS,
});

export default DEFAULT_ECN_RULESET;
